### ISSUE TITLE
[Bug] Randint error in `trim_and_preprocess()` during model training

### ISSUE THREAD

**Issue by poohcom1** [rodrigo-castellon/midi2params#1]
Hello!
I've been trying to train a model using my own data, but I ran into an error when running the trainscript file:
```sh
Epoch #1
yee_bach_passion#2
[Instrument(program=0, is_drum=False, name="")]
yee_bach_passion#41
[Instrument(program=0, is_drum=False, name="")]
...
yee_bach_passion#1
[Instrument(program=0, is_drum=False, name="")]
yee_bach_passion#21
[Instrument(program=0, is_drum=False, name="")]
Traceback (most recent call last):
  File "midi2params/trainscript.py", line 409, in <module>
    main()
  File "midi2params/trainscript.py", line 155, in main
    batch = trim_and_preprocess(batch, config)
  File "/home/poohcom1/midi2params_env/midi2params/midi2params/train_utils.py", line 93, in trim_and_preprocess
    subclip_start = np.random.randint(50, final_idx - 50 - len_subclip)
  File "mtrand.pyx", line 748, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1247, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high
```

This always happens during the first epoch after the program printed a few file. 

I'm still not familiar with the code base so I'm not sure how the upper limit is being calculated, and whether the issue has something to do with my dataset, so any pointers would be appreciated!

Cheers

**Comment by rodrigo-castellon** [comment]
Hello,
Thanks for asking this great question!
### My suggestion

Change `len_subclip` in the config file you're using to 1 second less than `len_clip`.

### Full Explanation / Background

So in this project we actually randomly subsample a subclip within a given example clip, where the subclip has a length strictly smaller than the length of the full clip. This is done for two reasons: (1) is to augment the data and (2), more importantly, is to allow for offsets. By offsets I mean that we will shift over the output targets to the future in the time axis. In effect, this offsetting will allow the model to see, let's say, a note in the MIDI input before it actually happens, and start predicting an increase in the loudness curve. Otherwise, it might already be too late for the model. The reason why we exclude 0.2 from each side is to avoid any potential issues with offsets exceeding the array bounds along the time dimension (this is explained somewhat vaguely as "wonky stuff" in the comment). Because of this, in the end, you should set `len_subclip` to be 1 second less (at least 0.4s at the minimum) than `len_clip` because this will make the subsampling step work.

Strangely enough, some experiments done after I wrote up this code (too late to revert) suggested that offsetting the labels so that the model can see future MIDI doesn't help at all... (also corroborated by an experiment that showed that unidirectional/bidirectional models perform similarly). This is why there are offset values of 0 in the config files; I actually stopped using any offsets after that experiment but because of the engineering hassle did not actually refactor to eliminate this configuration option...

FYI, I am planning on slowly cleaning this repository up / documenting it to increase reproducibility, as I am realizing that much of it is not documented very well...

Let me know if you have any further questions!

**Comment by poohcom1** [comment]
Thanks so much for your response! 

I've done what you've suggested to trained my data a while back just out of trial and error and it worked perfectly fine; I just wasn't sure about the reason, so thank you for the extensive explanation! I'm also glad to hear about the refactoring and Docker image; hopefully I'll be able to merge your changes since I did make a lot changes on my own fork haha.

Although it isn't really related to the thread issue, one thing I did wanted to ask about was the possibility of using the model real time, since I recall that being mentioned in the paper somewhere. I'm interested in making a GUI application for this model, so the ability to run the model in real time would be very helpful.

Thanks again for answering my questions, and I look forward to future updates!

**Comment by rodrigo-castellon** [comment]
Great! I see. I hope so too, I was planning to make not-too-many breaking changes to the code, and instead focus on simply reproducing/documenting what currently exists. Hopefully that would help you and others, potentially.

Re real-time: I think real-time is a cool direction! At the time of working on the project (circa summer 2020), we (Chris and I) had been working on an AudioWorklet version of DDSP, as there wasn't really any real-time options for DDSP; this didn't end up materializing into a finished interface, though. Since then, it appears that there has been [some work](http://ceur-ws.org/Vol-2903/IUI21WS-HAIGEN-3.pdf) on getting DDSP to run super fast on CPU with Javascript. The midi2params model is small enough that it should be able to run in real-time as well, so I'm confident end-to-end is possible. Might require some significant engineering effort, though. Let me know how it goes!
